services:

    Dontdrinkandroot\CrudAdminBundle\Service\Item\DoctrineItemProvider:
        arguments:
            - '@doctrine'
        tags:
            -   name: 'ddr_crud_admin.item_provider'
                priority: -200

    Dontdrinkandroot\CrudAdminBundle\Service\PaginationTarget\DoctrinePaginationTargetProvider:
        arguments:
            - '@doctrine'
            - !tagged_iterator ddr_crud_admin.query_builder_extension_provider
        tags:
            -   name: 'ddr_crud_admin.pagination_target_provider'
                priority: -200

    Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinition\DoctrineFieldDefinitionsProvider:
        arguments:
            - '@doctrine'
            - '@translator'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\TranslationDomain\TranslationDomainResolver'
        tags:
            -   name: 'ddr_crud_admin.field_definitions_provider'
                priority: -200

    Dontdrinkandroot\CrudAdminBundle\Service\Form\DoctrineFormProvider:
        arguments:
            - '@doctrine'
            - '@form.factory'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\TranslationDomain\TranslationDomainResolver'
        tags:
            - { name: 'ddr_crud_admin.form_provider', priority: -250 }

    Dontdrinkandroot\CrudAdminBundle\Service\Persister\DoctrineItemPersisterProvider:
        arguments:
            - '@doctrine'
        tags:
            -   name: 'ddr_crud_admin.item_persister_provider'
                priority: -200

    Dontdrinkandroot\CrudAdminBundle\Service\Id\DoctrineIdProvider:
        arguments:
            - '@doctrine'
            - '@property_accessor'
        tags:
            -   name: 'ddr_crud_admin.id_provider'
                priority: -200
