services:

    Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\FieldRenderer:
        arguments:
            - !tagged_iterator ddr_crud_admin.field_renderer_provider

    Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\NullRendererProvider:
        tags:
            - { name: 'ddr_crud_admin.field_renderer_provider', priority: -230 }

    Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\DateTimeRendererProvider:
        tags:
            - { name: 'ddr_crud_admin.field_renderer_provider', priority: -240 }

    Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\ArrayRendererProvider:
        tags:
            - { name: 'ddr_crud_admin.field_renderer_provider', priority: -240 }

    Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\JsonRendererProvider:
        tags:
            - { name: 'ddr_crud_admin.field_renderer_provider', priority: -240 }

    Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\DateRendererProvider:
        tags:
            - { name: 'ddr_crud_admin.field_renderer_provider', priority: -240 }

    Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\DecimalRendererProvider:
        tags:
            - { name: 'ddr_crud_admin.field_renderer_provider', priority: -240 }

    Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\ToStringRendererProvider:
        tags:
            - { name: 'ddr_crud_admin.field_renderer_provider', priority: -250 }
