imports:
    - { resource: field_definition_renderer.yaml }

services:

    Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.title_provider

    Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinition\FieldDefinitionsResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.field_definitions_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Pagination\PaginationResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.pagination_provider

    Dontdrinkandroot\CrudAdminBundle\Service\PaginationTarget\PaginationTargetResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.pagination_target_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.item_provider

    Dontdrinkandroot\CrudAdminBundle\Service\RouteInfo\RouteInfoResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.route_info_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplateResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.template_provider

    Dontdrinkandroot\CrudAdminBundle\Service\FormType\FormTypeResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.form_type_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.form_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister:
        arguments:
            - !tagged_iterator ddr_crud_admin.item_persister_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Id\IdResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.id_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Url\UrlResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.url_provider

    Dontdrinkandroot\CrudAdminBundle\Service\TranslationDomain\TranslationDomainResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.translation_domain_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Title\ToStringTitleProvider:
        tags:
            -   name: 'ddr_crud_admin.title_provider'
                priority: -240

    Dontdrinkandroot\CrudAdminBundle\Service\Title\DefaultTitleProvider:
        autowire: true
        tags:
            -   name: 'ddr_crud_admin.title_provider'
                priority: -250

    Dontdrinkandroot\CrudAdminBundle\Service\Pagination\DefaultPaginationProvider:
        arguments:
            - '@knp_paginator'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\PaginationTarget\PaginationTargetResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinition\FieldDefinitionsResolver'
            - '@request_stack'
        tags:
            -   name: 'ddr_crud_admin.pagination_provider'
                priority: -250

    Dontdrinkandroot\CrudAdminBundle\Service\Template\DefaultTemplateProvider:
        tags:
            -   name: 'ddr_crud_admin.template_provider'
                priority: -250

    Dontdrinkandroot\CrudAdminBundle\Service\RouteInfo\DefaultRouteInfoProvider:
        tags:
            -   name: 'ddr_crud_admin.route_info_provider'
                priority: -250

    Dontdrinkandroot\CrudAdminBundle\Service\NewInstance\DefaultNewInstanceProvider:
        tags:
            - { name: 'ddr_crud_admin.new_instance_provider', priority: -250 }

    Dontdrinkandroot\CrudAdminBundle\Service\Url\DefaultUrlProvider:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\RouteInfo\RouteInfoResolver'
            - '@router'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Id\IdResolver'
        tags:
            - { name: 'ddr_crud_admin.url_provider', priority: -250 }

    Dontdrinkandroot\CrudAdminBundle\Service\Form\FormTypeFormProvider:
        arguments:
            - '@form.factory'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FormType\FormTypeResolver'
        tags:
            - { name: 'ddr_crud_admin.form_provider', priority: -200 }

    Dontdrinkandroot\CrudAdminBundle\Service\TranslationDomain\DefaultTranslationDomainProvider:
        tags:
            - { name: 'ddr_crud_admin.translation_domain_provider', priority: -250 }

    Dontdrinkandroot\CrudAdminBundle\Twig\CrudAdminExtension:
        arguments:
            - '@property_accessor'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FieldRenderer\FieldRenderer'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Url\UrlResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver'
        tags:
            - { name: twig.extension }

    Dontdrinkandroot\CrudAdminBundle\Service\CrudControllerRegistry:
        arguments:
            - !tagged_iterator ddr_crud_admin.controller

    Dontdrinkandroot\CrudAdminBundle\Routing\CrudRoutesLoader:
        arguments:
            - !tagged_iterator ddr_crud_admin.controller
            - '@Dontdrinkandroot\CrudAdminBundle\Service\RouteInfo\RouteInfoResolver'
        tags: [ 'routing.loader' ]

    Dontdrinkandroot\CrudAdminBundle\Command\InfoCommand:
        autoconfigure: true
        autowire: true
