services:

    Dontdrinkandroot\CrudAdminBundle\Service\TitleProvider\DoctrineTitleProvider:
        tags:
            -
                name: 'ddr_crud_admin.title_provider'
                priority: 255

    Dontdrinkandroot\CrudAdminBundle\Service\ItemProvider\DoctrineItemProvider:
        arguments:
            - '@doctrine'
        tags:
            -
                name: 'ddr_crud_admin.item_provider'
                priority: 255

    Dontdrinkandroot\CrudAdminBundle\Service\CollectionProvider\DoctrineCollectionProvider:
        arguments:
            - '@doctrine'
            - '@knp_paginator'
        tags:
            -
                name: 'ddr_crud_admin.collection_provider'
                priority: 255

    Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitionProvider\DoctrineFieldDefinitionProvider:
        arguments:
            - '@doctrine'
        tags:
            -
                name: 'ddr_crud_admin.field_definition_provider'
                priority: 255

    Dontdrinkandroot\CrudAdminBundle\Service\FormProvider\DoctrineFormProvider:
        arguments:
            - '@doctrine'
            - '@form.factory'
        tags:
            -
                name: 'ddr_crud_admin.form_provider'
                priority: 255
