services:

    Dontdrinkandroot\CrudAdminBundle\Service\Title\DoctrineTitleProvider:
        tags:
            -   name: 'ddr_crud_admin.title_provider'
                priority: 200

    Dontdrinkandroot\CrudAdminBundle\Service\Item\DoctrineItemProvider:
        arguments:
            - '@doctrine'
        tags:
            -   name: 'ddr_crud_admin.item_provider'
                priority: 200

    Dontdrinkandroot\CrudAdminBundle\Service\Collection\DoctrineCollectionProvider:
        arguments:
            - '@doctrine'
            - '@knp_paginator'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\FieldDefinitionsResolver'
        tags:
            -   name: 'ddr_crud_admin.collection_provider'
                priority: 200

    Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\DoctrineFieldDefinitionProvider:
        arguments:
            - '@doctrine'
        tags:
            -   name: 'ddr_crud_admin.field_definitions_provider'
                priority: 200

    Dontdrinkandroot\CrudAdminBundle\Service\Form\DoctrineFormProvider:
        arguments:
            - '@doctrine'
            - '@form.factory'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
        tags:
            -   name: 'ddr_crud_admin.form_provider'
                priority: 200

    Dontdrinkandroot\CrudAdminBundle\Service\Persister\DoctrineItemPersisterProvider:
        arguments:
            - '@doctrine'
        tags:
            -   name: 'ddr_crud_admin.item_persister_provider'
                priority: 200
