services:

    Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.title_provider

    Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\FieldDefinitionsResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.field_definitions_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Pagination\PaginationResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.pagination_provider

    Dontdrinkandroot\CrudAdminBundle\Service\PaginationTarget\PaginationTargetResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.pagination_target_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.item_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.routes_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplatesResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.templates_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.form_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister:
        arguments:
            - !tagged_iterator ddr_crud_admin.item_persister_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Id\IdResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.id_provider

    Dontdrinkandroot\CrudAdminBundle\Service\NewInstance\NewInstanceResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.new_instance_provider

    Dontdrinkandroot\CrudAdminBundle\Service\Url\UrlResolver:
        arguments:
            - !tagged_iterator ddr_crud_admin.url_provider


    Dontdrinkandroot\CrudAdminBundle\Event\Listener\DefaultListResponseListener:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Pagination\PaginationResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\FieldDefinitionsResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplatesResolver'
            - '@twig'
        tags:
            -   name: 'kernel.event_listener'
                event: Dontdrinkandroot\CrudAdminBundle\Event\CreateResponseEvent
                method: 'onCreateResponseEvent'
                priority: 50

    Dontdrinkandroot\CrudAdminBundle\Event\Listener\DefaultReadResponseListener:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\FieldDefinitionsResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplatesResolver'
            - '@twig'
        tags:
            -   name: 'kernel.event_listener'
                event: Dontdrinkandroot\CrudAdminBundle\Event\CreateResponseEvent
                method: 'onCreateResponseEvent'
                priority: 50

    Dontdrinkandroot\CrudAdminBundle\Event\Listener\DefaultCreateUpdateResponseListener:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplatesResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver'
            - '@twig'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Url\UrlResolver'
        tags:
            -   name: 'kernel.event_listener'
                event: Dontdrinkandroot\CrudAdminBundle\Event\CreateResponseEvent
                method: 'onCreateResponseEvent'
                priority: 50

    Dontdrinkandroot\CrudAdminBundle\Event\Listener\DefaultDeleteResponseListener:
        arguments:
            - '@router'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Url\UrlResolver'
        tags:
            -   name: 'kernel.event_listener'
                event: Dontdrinkandroot\CrudAdminBundle\Event\CreateResponseEvent
                method: 'onCreateResponseEvent'
                priority: 50

    Dontdrinkandroot\CrudAdminBundle\Action\ListAction:
        arguments:
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Action\CreateAction:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\NewInstance\NewInstanceResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister'
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Action\ReadAction:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Action\UpdateAction:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister'
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Action\DeleteAction:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister'
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Service\Title\DefaultTitleProvider:
        tags:
            -   name: 'ddr_crud_admin.title_provider'
                priority: -250

    Dontdrinkandroot\CrudAdminBundle\Service\Pagination\DefaultPaginationProvider:
        arguments:
            - '@knp_paginator'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\PaginationTarget\PaginationTargetResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\FieldDefinitionsResolver'
        tags:
            -   name: 'ddr_crud_admin.pagination_provider'
                priority: -250

    Dontdrinkandroot\CrudAdminBundle\Service\Routes\DefaultRoutesProvider:
        arguments:
            - '@router'
        tags:
            -   name: 'ddr_crud_admin.routes_provider'
                priority: -250

    Dontdrinkandroot\CrudAdminBundle\Service\Template\DefaultTemplatesProvider:
        tags:
            -   name: 'ddr_crud_admin.templates_provider'
                priority: -250

    Dontdrinkandroot\CrudAdminBundle\Service\Form\RequestAttributeFormProvider:
        arguments:
            - '@form.factory'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
        tags:
            - { name: 'ddr_crud_admin.form_provider', priority: -50 }

    Dontdrinkandroot\CrudAdminBundle\Service\NewInstance\DefaultNewInstanceProvider:
        tags:
            - { name: 'ddr_crud_admin.new_instance_provider', priority: -250 }

    Dontdrinkandroot\CrudAdminBundle\Service\Url\DefaultUrlProvider:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver'
            - '@router'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Id\IdResolver'
            - '@security.authorization_checker'
        tags:
            - { name: 'ddr_crud_admin.url_provider', priority: -250 }

    Dontdrinkandroot\CrudAdminBundle\Twig\CrudAdminExtension:
        arguments:
            - '@property_accessor'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Id\IdResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Url\UrlResolver'
            - '@request_stack'
        tags:
            - { name: twig.extension }

    Dontdrinkandroot\CrudAdminBundle\Routing\EntityLoader:
        arguments:
            - '@file_locator'
        tags:
            - { name: routing.loader }
