services:

    Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver: ~

    Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\FieldDefinitionsResolver: ~

    Dontdrinkandroot\CrudAdminBundle\Service\Collection\CollectionResolver: ~

    Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver: ~

    Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver: ~

    Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplateResolver: ~

    Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver: ~

    Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister: ~

    Dontdrinkandroot\CrudAdminBundle\Service\Id\IdResolver: ~

    Dontdrinkandroot\CrudAdminBundle\Event\Listener\DefaultListResponseListener:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Collection\CollectionResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\FieldDefinitionsResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplateResolver'
            - '@twig'
        tags:
            -   name: 'kernel.event_listener'
                event: Dontdrinkandroot\CrudAdminBundle\Event\CreateResponseEvent
                method: 'onCreateResponseEvent'

    Dontdrinkandroot\CrudAdminBundle\Event\Listener\DefaultReadResponseListener:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\FieldDefinitions\FieldDefinitionsResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplateResolver'
            - '@twig'
        tags:
            -   name: 'kernel.event_listener'
                event: Dontdrinkandroot\CrudAdminBundle\Event\CreateResponseEvent
                method: 'onCreateResponseEvent'

    Dontdrinkandroot\CrudAdminBundle\Event\Listener\DefaultCreateUpdateResponseListener:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Template\TemplateResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Title\TitleResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Id\IdResolver'
            - '@twig'
            - '@router'
        tags:
            -   name: 'kernel.event_listener'
                event: Dontdrinkandroot\CrudAdminBundle\Event\CreateResponseEvent
                method: 'onCreateResponseEvent'

    Dontdrinkandroot\CrudAdminBundle\Event\Listener\DefaultDeleteResponseListener:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Routes\RoutesResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@router'
        tags:
            -   name: 'kernel.event_listener'
                event: Dontdrinkandroot\CrudAdminBundle\Event\CreateResponseEvent
                method: 'onCreateResponseEvent'

    Dontdrinkandroot\CrudAdminBundle\Action\ListAction:
        arguments:
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Action\CreateAction:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister'
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Action\ReadAction:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Action\UpdateAction:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Form\FormResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister'
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Action\DeleteAction:
        arguments:
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Item\ItemResolver'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Persister\ItemPersister'
            - '@security.authorization_checker'
            - '@event_dispatcher'
        tags: ['controller.service_arguments']

    Dontdrinkandroot\CrudAdminBundle\Service\Title\DefaultTitleProvider:
        tags:
            -   name: 'ddr_crud_admin.title_provider'
                priority: 250

    Dontdrinkandroot\CrudAdminBundle\Service\Routes\DefaultRoutesProvider:
        tags:
            -   name: 'ddr_crud_admin.routes_provider'
                priority: 250

    Dontdrinkandroot\CrudAdminBundle\Service\Template\DefaultTemplateProvider:
        tags:
            -   name: 'ddr_crud_admin.template_provider'
                priority: 250

    Dontdrinkandroot\CrudAdminBundle\Twig\CrudAdminExtension:
        arguments:
            - '@property_accessor'
            - '@Dontdrinkandroot\CrudAdminBundle\Service\Id\IdResolver'
        tags:
            - { name: twig.extension }
