list:
    path: ''
    controller: Dontdrinkandroot\CrudAdminBundle\Action\ListAction

create:
    path: '__NEW__/edit'
    controller: Dontdrinkandroot\CrudAdminBundle\Action\CreateAction

update:
    path: '{id}/edit'
    controller: Dontdrinkandroot\CrudAdminBundle\Action\UpdateAction

delete:
    path: '{id}/delete'
    controller: Dontdrinkandroot\CrudAdminBundle\Action\DeleteAction

read:
    path: '{id}'
    controller: Dontdrinkandroot\CrudAdminBundle\Action\ReadAction
